### ISSUE TITLE
Administration unavailable under XH 1.7

### ISSUE THREAD

**Issue by frase-git** [cmb69/dlcounter_xh#9]
Keinerlei Anzeige im Backend.
Keine Fehlermeldungen.

**Comment by cmb69** [comment]
Ah, danke!

### Quick fix

[Diese Zeile](https://github.com/cmb69/dlcounter_xh/blob/1alpha1/admin.php#L181) ersetzen durch:
````
if (XH_wantsPluginAdministration('dlcounter')) {
````
